### ISSUE TITLE
How can I use G4mismatch without GPU?

### ISSUE THREAD

**Issue by Z-H-Zhang** [OrensteinLab/G4mismatch#1]
2024-03-02 15:55:08.273914: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer.so.6'; dlerror: libnvinfer.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/gridview/pbs/dispatcher/lib:/public/software/compiler/intel/composer_xe_2016.3.210/compiler/lib/intel64:/public/software/compiler/intel/composer_xe_2016.3.210/mkl/lib/intel64:/public/software/compiler/intel/composer_xe_2016.2.181/compiler/lib/intel64:/public/software/compiler/intel/composer_xe_2016.2.181/mkl/lib/intel64::/usr/local/lib64:/usr/local/lib
2024-03-02 15:55:08.274936: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libnvinfer_plugin.so.6'; dlerror: libnvinfer_plugin.so.6: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/gridview/pbs/dispatcher/lib:/public/software/compiler/intel/composer_xe_2016.3.210/compiler/lib/intel64:/public/software/compiler/intel/composer_xe_2016.3.210/mkl/lib/intel64:/public/software/compiler/intel/composer_xe_2016.2.181/compiler/lib/intel64:/public/software/compiler/intel/composer_xe_2016.2.181/mkl/lib/intel64::/usr/local/lib64:/usr/local/lib
2024-03-02 15:55:08.274988: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:30] Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
2024-03-02 15:56:35.930595: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /opt/gridview/pbs/dispatcher/lib:/public/software/compiler/intel/composer_xe_2016.3.210/compiler/lib/intel64:/public/software/compiler/intel/composer_xe_2016.3.210/mkl/lib/intel64:/public/software/compiler/intel/composer_xe_2016.2.181/compiler/lib/intel64:/public/software/compiler/intel/composer_xe_2016.2.181/mkl/lib/intel64::/usr/local/lib64:/usr/local/lib
2024-03-02 15:56:35.930666: E tensorflow/stream_executor/cuda/cuda_driver.cc:351] failed call to cuInit: UNKNOWN ERROR (303)
2024-03-02 15:56:35.930712: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (login1): /proc/driver/nvidia/version does not exist
Traceback (most recent call last):
  File "/home/zhzhang/software/G4mismatch-master/G4mismatch_scan.py", line 152, in <module>
    main(args)
  File "/home/zhzhang/software/G4mismatch-master/G4mismatch_scan.py", line 68, in main
    model = load_model(args['model_path'], custom_objects={"pearson": pearson}, compile=False)
  File "/home/zhzhang/miniconda3/envs/DeepG4/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/save.py", line 146, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/zhzhang/miniconda3/envs/DeepG4/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/hdf5_format.py", line 168, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/zhzhang/miniconda3/envs/DeepG4/lib/python3.7/site-packages/tensorflow_core/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/zhzhang/miniconda3/envs/DeepG4/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/serialization.py", line 106, in deserialize
    printable_module_name='layer')
  File "/home/zhzhang/miniconda3/envs/DeepG4/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 292, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/zhzhang/miniconda3/envs/DeepG4/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 250, in class_and_config_for_serialized_keras_object
    raise ValueError('Unknown ' + printable_module_name + ': ' + class_name)
ValueError: Unknown layer: Functional

**Comment by OrensteinLab** [comment]
import os

# Set CUDA_VISIBLE_DEVICES to an empty string
os.environ['CUDA_VISIBLE_DEVICES'] = ''
